const mockData = [ { Version: 1,
    Key: '14-349727_1_AL',
    Type: 'City',
    Rank: 15,
    LocalizedName: 'New York City',
    EnglishName: 'New York',
    PrimaryPostalCode: '10007',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NY',
       LocalizedName: 'New York',
       EnglishName: 'New York',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.779, Longitude: -73.969, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [ [Object] ],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '2-9941_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'Essex County Airport',
    EnglishName: 'Essex County Airport',
    PrimaryPostalCode: '07004',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NJ',
       LocalizedName: 'New Jersey',
       EnglishName: 'New Jersey',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.875, Longitude: -74.281, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '4-10358_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'John F Kennedy International Airport',
    EnglishName: 'John F Kennedy International Airport',
    PrimaryPostalCode: '11430',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NY',
       LocalizedName: 'New York',
       EnglishName: 'New York',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.64, Longitude: -73.779, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '5-9508_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'La Guardia Airport',
    EnglishName: 'La Guardia Airport',
    PrimaryPostalCode: '11371',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NY',
       LocalizedName: 'New York',
       EnglishName: 'New York',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.777, Longitude: -73.873, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '2-6483_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'Lincoln Park Airport',
    EnglishName: 'Lincoln Park Airport',
    PrimaryPostalCode: '07035',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NJ',
       LocalizedName: 'New Jersey',
       EnglishName: 'New Jersey',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.947, Longitude: -74.314, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '2-8851_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'Linden Airport',
    EnglishName: 'Linden Airport',
    PrimaryPostalCode: '07036',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NJ',
       LocalizedName: 'New Jersey',
       EnglishName: 'New Jersey',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.617, Longitude: -74.245, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '2-6979_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'Morristown Municipal Airport',
    EnglishName: 'Morristown Municipal Airport',
    PrimaryPostalCode: '07960',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NJ',
       LocalizedName: 'New Jersey',
       EnglishName: 'New Jersey',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.799, Longitude: -74.415, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '2-7761_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'Newark Liberty International Airport',
    EnglishName: 'Newark Liberty International Airport',
    PrimaryPostalCode: '07114',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NJ',
       LocalizedName: 'New Jersey',
       EnglishName: 'New Jersey',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.693, Longitude: -74.169, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '2-8889_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'Teterboro Airport',
    EnglishName: 'Teterboro Airport',
    PrimaryPostalCode: '07608',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NJ',
       LocalizedName: 'New Jersey',
       EnglishName: 'New Jersey',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 40.85, Longitude: -74.061, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] },
  { Version: 1,
    Key: '2-8628_1_POI_AL',
    Type: 'POI',
    Rank: 250,
    LocalizedName: 'Westchester County Airport',
    EnglishName: 'Westchester County Airport',
    PrimaryPostalCode: '10604',
    Region: 
     { ID: 'NAM',
       LocalizedName: 'North America',
       EnglishName: 'North America' },
    Country: 
     { ID: 'US',
       LocalizedName: 'United States',
       EnglishName: 'United States' },
    AdministrativeArea: 
     { ID: 'NY',
       LocalizedName: 'New York',
       EnglishName: 'New York',
       Level: 1,
       LocalizedType: 'State',
       EnglishType: 'State',
       CountryID: 'US' },
    TimeZone: 
     { Code: 'EST',
       Name: 'America/New_York',
       GmtOffset: -5,
       IsDaylightSaving: false,
       NextOffsetChange: '2017-03-12T07:00:00Z' },
    GeoPosition: { Latitude: 41.067, Longitude: -73.708, Elevation: [Object] },
    IsAlias: true,
    SupplementalAdminAreas: [],
    DataSets: [ 'Alerts', 'ForecastConfidence', 'MinuteCast' ] } ]

module.exports = mockData;